package com.hr.personnel;

public class Person {
  
  // VARIABLES
  private String name;
  private int age;
  private double height;
  private double weight;
  
  // CONSTRUCTORS
  public Person() {
  }
  
  public Person(String name) {
    this.setName(name);
  }
  
  public Person(String name, int age) {
    this.setName(name);
    this.setAge(age);
  }
  
  public Person(String name, int age, double height, double weight) {
    this.setName(name);
    this.setAge(age);
    this.setHeight(height);
    this.setWeight(weight);
  }
  
  // BEHAVIORAL METHODS
  public double calculateBMI() {
    return weight / height;
  }
  
  public void eat() {
    System.out.println(this.getName() + " is eating my favorite food");
  }
  
  public void eat(String food) {
    if (food.equals("pizza")) { 
      System.out.println("Sorry, I don't eat pizza");
    }
    else {
      System.out.println(this.getName() + " is eating " + food);
    }
  }
  
  // ACCESSOR METHODS
  public String getName() {
    return this.name;
  }
  public void setName(String name) {
    this.name = name;
  }
  
  public int getAge() {
    return this.age;
  }
  public void setAge(int age) {
    if (age > 0) {
      this.age = age;
    }
  }
  
  public double getHeight() {
    return this.height;
  }
  public void setHeight(double height) {
    this.height = height;
  }
  
  public double getWeight() {
    return this.weight;
  }
  public void setWeight(double weight) {
    this.weight = weight;
  }
  
  /* generated by the IDE
  public int hashCode() {
    System.out.println("*** Person.hashCode() ***");
    final int prime = 31;
    int result = 1;
    result = prime * result + this.age;
    long temp;
    temp = Double.doubleToLongBits(this.height);
    result = prime * result + (int) (temp ^ (temp >>> 32));
    result = prime * result + ((this.name == null) ? 0 : this.name.hashCode());
    temp = Double.doubleToLongBits(this.weight);
    result = prime * result + (int) (temp ^ (temp >>> 32));
    return result;
  }
  */
  
  /*
   * Adds the hash codes of all 4 instance variables.
   */
  public int hashCode() {
    System.out.println("*** Person.hashCode() ***");
    return this.getName().hashCode() + 
      new Integer(this.getAge()).hashCode() +
      new Double(this.getHeight()).hashCode() +
      new Double(this.getWeight()).hashCode();
  }
  
  /*
   * Two Persons are equal if all 4 instance variables are equal.
   */
  public boolean equals(Object obj) {
    System.out.println("*** Person.equals() ***");
    boolean result = false;
    if (obj instanceof Person) {
      Person other = (Person) obj;
      result = this.getName().equals(other.getName()) &&
        this.getAge() == other.getAge() &&
        this.getHeight() == other.getHeight() &&
        this.getWeight() == other.getWeight();
    }
    return result;
  }
  
  public String toString() {
    return "Person [name=" + this.getName() + ", age=" + this.getAge() + ", height="
      + this.getHeight() + ", weight=" + this.getWeight() + "]";
  }
}